name: Actions Workflow

on: push

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        id: greet
        uses: kamotenglanot/hello-world-javascript-action@v1
        with:
          who-to-greet: John
      - name: Log Greeting Time
        uses: echo "${{ steps.greet.outputs.time }}"