name: Shell Commands

on: push

jobs:
  run-shell_command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: eccho "Hello World"
      - name: multiline script
        run: |
          node -v
          npm -v
